name: byao_native_app
description: Une application native haute performance pour l'écosystème BYAO.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
  sdk: flutter
  # Maktaba rasmi ya kuweka matangazo ya AdMob
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
